id: IA76DD2AA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T10:45:48+00:00'
last_modified: '2022-06-07T13:37:27.507038+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30522
  title: བཤད་པའི་རྒྱུད་ཀྱི་རྣམ་བཤད་ནོར་བུ་ཕྲེང་མཛེས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    9BAA:
      image_group_id: I1KG21918
      title: ''
      total_pages: 342
      order: 1
      base_file: 9BAA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
