id: P000747
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-16 16:40:42.706857
source_metadata:
  id: bdr:W30522
  title: བཤད་པའི་རྒྱུད་ཀྱི་རྣམ་བཤད་ནོར་བུ་ཕྲེང་མཛེས།
  author: ''
  volumes:
    6a2acac25c6a4374830e3393c0dc9011:
      image_group_id: I1KG21918
      title: ''
      volume_number: 1
      total_pages: 342
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
